# Generated by Django 3.2.10 on 2023-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_chatbotusers_chatbotuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotuser',
            options={},
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='language_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
